# Generated by Django 5.0.6 on 2024-07-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('past_date', models.DateField()),
                ('style', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('purchase_link', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('story', models.TextField(default='', max_length=5000)),
                ('image_1', models.ImageField(upload_to='media/artImage')),
                ('image_2', models.ImageField(upload_to='media/artImage')),
                ('image_3', models.ImageField(upload_to='media/artImage')),
                ('image_4', models.ImageField(upload_to='media/artImage')),
                ('image_5', models.ImageField(upload_to='media/artImage')),
                ('image_6', models.ImageField(upload_to='media/artImage')),
            ],
        ),
    ]
