# Generated by Django 5.0.6 on 2024-07-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KultureKorner_postArt', '0002_alter_postart_image_1_alter_postart_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postart',
            old_name='past_date',
            new_name='post_date',
        ),
    ]
